[versions]
slf4j = "2.0.9" # SLF4J releases: http://www.slf4j.org/news.html
logback = "1.4.14" # Logback releases: http://logback.qos.ch/download.html

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
